version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_RUN_HOST=0.0.0.0
      - LASTFM_API_KEY=your_api_key_here
      - LASTFM_USERNAME=your_username_here

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend